### ISSUE TITLE
Error (EDokanMainError): Dokan Error. Code: -3.

### ISSUE THREAD

**Issue by iav** [alexpmorris/dipfs#2]
DokanInstall_0.6.0.exe, https://github.com/alexpmorris/dipfs/releases/download/0.12/dipfs.exe
Windows 7 x64.
C:\Users\xxx>dipfs /l y /d
dipfs v0.12: Mounting ipfs [y:\ipfs\, y:\ipns] via http://127.0.0.1:5001/api
Error (EDokanMainError): Dokan Error. Code: -3.
Cannot install driver

What's wrong?

**Comment by alexpmorris** [comment]
Does the dokan demo app work for you (included in the dokaninstall)?  And did you try running from an Administrator Command Prompt?  Also, you should probably try using the latest dokany version from https://github.com/dokan-dev/dokany/releases

**Comment by iav** [comment]
I setup https://github.com/dokan-dev/dokany/releases/download/v1.0.0-RC1/DokanSetup.exe first, but with them dipfs can't start, claiming to dokan.dll not found. Sure, dokany provides only docan1.dll, not docan.dll.
No, I run bot from administrator prompt, but user have administrator rights.
I don't know about a dokan demo program, because there no one word how to use it. One I can say - I run it, and got command-line help, than gives no help to people without knowledge what should it do at all. I can try to run a commad if you give me command line, or point another way "what should it do".

**Comment by alexpmorris** [comment]
Try following the directions they give on the following thread.  It also shows you how to test the dokan demo program (mirror.exe): https://github.com/dokan-dev/dokany/issues/170 (Can't find dokan1.dll #170).  dipfs is based on the dokan mirror demo, so if you get one working, so should dipfs.

**Comment by iav** [comment]
Sorry, there was a mistype In my comment https://github.com/alexpmorris/dipfs/issues/2#issuecomment-189762061 (now corrected). Not docan1.dll, bbut docan.dll. It means dipfs looks for docan 0.6, not docany?

**Comment by iav** [comment]
with docan o.6 sample runs as follow:

```
C:\...Dokan\DokanLibrary\sample\mirror>mirror.exe /s /d /r c:\Temp /l m
RootDirectory: c:\Temp
Dokan: debug mode on
Dokan: use stderr
Dokan Error: CreatFile Failed \\.\Dokan: 2
Can't install driver
```

**Comment by alexpmorris** [comment]
It sounds like it's probably not finding the right DLL on your system for some reason.  Also, if you try different versions of Dokan, make sure you uninstall the previous versions just as a precaution.  Finally, I found this via google that maybe can help you: https://groups.google.com/forum/#!topic/dokan/yuaLtF1CpZw (Re: [Dokan] Installer does not install dokan.dll on 64 bit Windows 7) 

Beyond that, really not sure, except to say that I did get both versions working on Windows7 64-bit, and that if you do get mirror.exe to work, so should dipfs.exe

**Comment by iav** [comment]
With Dokany from https://github.com/dokan-dev/dokany/issues/170#issuecomment-184892001 I have running mirror sample: it create me drive M: with content from my temp folder.

But it does nothing with fach that dokany contains only dokan1.dll, but dipfs.exe looks for dokan.dll. 
Maybe, I can take a dipfs fresher than https://github.com/alexpmorris/dipfs/releases/download/0.12/dipfs.exe, linked with dokan1.dll?

**Comment by alexpmorris** [comment]
It seems the newer versions of dokany released in the past few months have breaking changes to the older versions that were compatible with the original 0.6.0 version.  In fact, I couldn't even get the latest 1.0.0 release candidate to work properly.  It kept saying the driver was unsigned.  However, after uninstalling that version, and reinstalling dokany v0.7.4, it worked first try without a hitch.  Try that version and hopefully that should do it: https://github.com/dokan-dev/dokany/releases/tag/v0.7.4

**Comment by iav** [comment]
Yes! Now it started.
Thank you!
